"""site and permission

Revision ID: 1b49bc3aacf5
Revises: 978d7e6c6e4a
Create Date: 2020-12-04 00:16:39.180429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b49bc3aacf5"
down_revision = "978d7e6c6e4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("published_url", sa.String(length=255), nullable=True),
        sa.Column("published_on", sa.DateTime(), nullable=True),
        sa.Column("subdomain", sa.String(length=128), nullable=True),
        sa.Column("bucket", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subdomain"),
    )
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column(
            "permissions",
            sa.Enum("owner_", "writer_", "reader_", name="permissions_values"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], name="fk_permission_site_id"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_permission_user_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permission")
    op.drop_table("site")
    # ### end Alembic commands ###
