"""first pass

Revision ID: 394f8236a753
Revises: 
Create Date: 2020-12-04 14:07:54.047558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "394f8236a753"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.JSON(), nullable=True),
        sa.Column("accl", sa.Text(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "site",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("published_url", sa.String(length=255), nullable=True),
        sa.Column("published_on", sa.DateTime(), nullable=True),
        sa.Column("subdomain", sa.String(length=128), nullable=True),
        sa.Column("bucket", sa.String(length=128), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("subdomain"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password", sa.String(length=64), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column(
            "permission",
            sa.Enum("reader", "writer", "owner", name="permissions_values"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["site.id"], name="fk_permission_site_id"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="fk_permission_user_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permission")
    op.drop_table("user")
    op.drop_table("site")
    op.drop_table("log")
    # ### end Alembic commands ###
