"""cognito

Revision ID: 553bab1649e7
Revises: 394f8236a753
Create Date: 2020-12-05 09:25:55.570068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "553bab1649e7"
down_revision = "394f8236a753"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("cognito", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "cognito")
    # ### end Alembic commands ###
